apiVersion: "v1"
kind: "Pod"
spec:
  containers:
    - name: "maven"
      image: "molgenis/maven-jdk17:1.0.0"
      command:
        - "cat"
      env:
        - name: "MAVEN_OPTS"
          value: "-Duser.home=/home/jenkins/agent"
        - name: "MAVEN_CONFIG"
          value: "/home/jenkins/agent/.m2"
        - name: "HOME"
          value: "/home/jenkins/agent"
      resources:
        requests:
          memory: "4Gi"
          cpu: "1"
      tty: true
    - name: elasticsearch
      image: molgenis/molgenis-elasticsearch:1.0.0
      resources:
        requests:
          cpu: "100m"
          memory: "1Gi"
        limits:
          memory: "1500Mi"
      env:
        - name: ES_JAVA_OPTS
          value: '-Xms512m -Xmx512m'
        - name: cluster.name
          value: molgenis
        - name: bootstrap.memory_lock
          value: 'true'
        - name: discovery.type
          value: single-node
    - name: postgres
      image: postgres:11-alpine
      resources:
        requests:
          cpu: "100m"
          memory: "250Mi"
        limits:
          memory: "250Mi"
      env:
        - name: POSTGRES_USER
          value: molgenis
        - name: POSTGRES_PASSWORD
          value: molgenis
        - name: POSTGRES_DB
          value: molgenis
    - name: minio
      image: minio/minio:RELEASE.2019-03-20T22-38-47Z
      env:
        - name: MINIO_ACCESS_KEY
          value: molgenis
        - name: MINIO_SECRET_KEY
          value: molgenis
      args:
        - server
        - /data